[package]
name = "cosmic-ext-storage-storage-sys"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true

[lib]
name = "storage_sys"
path = "src/lib.rs"
