name = "2disk"
artifacts_root = "target/storage-testing/images/2disk"
partition_table = "gpt"

[[images]]
file_name = "disk0.img"
size_bytes = 2147483648

[[images]]
file_name = "disk1.img"
size_bytes = 2147483648

[[partitions]]
index = 1
start = "1MiB"
end = "100%"
type = "primary"
fs = "ext4"

[[mounts]]
partition_ref = "p1"
mount_point = "/mnt/storage-testing/2disk/disk0p1"
